name: Metrics
on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches:
      - master
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          config_timezone: Europe/Stockholm
          repositories: 350
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_limit: 12
          plugin_notable: yes
          plugin_lines: yes
